name: Documentation

on:
  push:
    branches: [ main, extensions ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
      isOldDoc: ${{ steps.diff.outputs.isOldDoc }}
    steps:
      - uses: actions/checkout@v3 # pin@v3
      - name: Detect Changes
        uses: './.github/actions/diffs'
        id: diff
  
  spelling:
    name: Lint documentation
    needs: diff
    if: needs.diff.outputs.isDoc == 'true'
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3 # pin@v3
      - name: Spell Check Docs
        uses: crate-ci/typos@v1.16.11
        with:
          files: ./docs/content

  old-doc-folder-notice:
    name: Old doc folder notice
    needs: diff
    if: needs.diff.outputs.isOldDoc == 'true'
    runs-on: [ubuntu-latest]

    steps:
      - name: Output error
        run: |
          echo "::error::Sui documentation has moved from doc/* to docs/content/* folder. (*.md files are now *.mdx)"
          exit 1
